### ISSUE TITLE
pretty print the type

### ISSUE THREAD

**Issue by MasseGuillaume** [lihaoyi/upickle-pprint#135]
PPrint could also show a simplified type

`> pprint.pprintln(Seq(1, 2, 3), showType = Simplified)`
`List(1,2,3): List[Int]`

`> pprint.pprintln(Seq(1, 2, 3), showType = Full)`
`List(1,2,3): scala.collection.immutable.List[Int]`

relevant: http://stackoverflow.com/questions/35400145/how-to-pretty-print-a-scala-type

**Comment by lihaoyi** [comment]
Already present in Ammonite

**Comment by lihaoyi** [comment]
Also, @MasseGuillaume you need to learn to provide better bug reports and/or communicate more clearly. This isn't the first time I've closed issues from you without a proper response, because most of the issues you've open are not proper issues. Come chat on Gitter first before you open your next issue and you're more likely to get what you want
