### ISSUE TITLE
Configurable sum encoding

### ISSUE THREAD

**Issue by tindzk** [lihaoyi/upickle-pprint#55]
I need to parse the [Pandoc format](https://github.com/jgm/pandoc-types/blob/master/Text/Pandoc/Definition.hs) which is produced via [aeson](https://hackage.haskell.org/package/aeson). aeson supports configuring the sum encoding which is done as follows in Pandoc:

```haskell
Aeson.sumEncoding = Aeson.TaggedObject "t" "c"
```

Obviously, this consumes more space than the current approach chosen by uPickle:

```scala
  def annotate[V: ClassTag](rw: R[V], n: String) = R[V]{
    case Js.Arr(Js.Str(`n`), x) => rw.read(x)
  }
```

Would it be possible to not import ``annotate`` by default, so that I could define it manually?

This feature would significantly increase interoperability with other picklers as there doesn't seem to be a common standard on how to serialise classes.

**Comment by lihaoyi** [comment]
Possible. Would require some thought as to how to make it work well. Not sure whether typeclasses or virtual-classes would be the way to go for this

**Comment by tindzk** [comment]
Here's my first attempt: https://github.com/tindzk/upickle/tree/change-sumencoding

It doesn't work as expected since the implicit is not resolved properly. Do you have any idea how to fix it?

**Comment by lihaoyi** [comment]
This is fixed in master https://github.com/lihaoyi/upickle-pprint/blob/master/upickle/shared/src/main/scala/upickle/Api.scala#L7-L40

Now you can define your own upickle bundle and override the CaseR/CaseW sum encoding, swap between the old array-wrapped typetags and type-attribute typetags, and other things. By default I provide `import upickle.legacy._` for the old encoding and `upickle.default` for a seemingly much-more-useful default encoding

**Comment by tindzk** [comment]
Great, thanks!
